name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore project dependencies
        run: dotnet restore LambdaWarmer/LambdaWarmer.csproj
      - name: Build project
        run: dotnet build LambdaWarmer/LambdaWarmer.csproj --no-restore --configuration Release
      - name: Pack project
        run: dotnet pack LambdaWarmer/LambdaWarmer.csproj --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
      - name: Publish package to NuGet
        run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_PUBLISH_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate